### ISSUE TITLE
Rive Renderer with Flutter?

### ISSUE THREAD

**Issue by MaoHolden** [rive-app/rive-runtime#22] opened 2024-09-17 23:25 UTC
The documentation mentions that when using Flutter its only possible to use Skia/Impeller, is this still true?

Are there any updates on Flutter support? Will it be possible in the near future?

Thank you <3

**Comment by HayesGordon** [comment] 2024-09-18 08:41
Soon! Our Flutter runtime required a bigger rework. We will be releasing a base package called `rive_native` to Pub, which will eventually be used in `rive_flutter`. Once `rive_native` launches you'll be able to use the Rive Renderer in Flutter, however, it will still be a few weeks before we do a major release of rive_flutter, at which point you can opt-in to use either Flutter's renderer or the Rive Renderer (for Rive content).

We have this issue on the public Flutter board: https://github.com/rive-app/rive-flutter/issues/388

I'll close this here as a duplicate of that.

**Closed by HayesGordon** 2024-09-18 08:41 UTC
